### ISSUE TITLE
dom-exception.ts

### ISSUE THREAD

**Issue by jimmywarting** [MattiasBuelens/web-streams-polyfill#109]
I thought instead of using a own custom DOMexception class, how about using this npm [package](https://github.com/jimmywarting/node-domexception) instead?

**Comment by MattiasBuelens** [comment]
That package appears to be Node-specific ([relying on `worker_threads`](https://github.com/jimmywarting/node-domexception/blob/2122879adda5f1971ff67673bec55cd8b3009cb6/index.js#L5)), whereas this polyfill targets both browsers *and* Node. 😕

That said, this polyfill will try to use `globalThis.DOMException` if it exists, so if you load `node-domexception` *before* loading `web-streams-polyfill` it should "just work". Yes, you'd still have an unused `DOMException` polyfill as part of `web-streams-polyfill`, but I guess there's always gonna be *some* dead code if you try to support multiple platforms. 🤷‍♂️

Maybe one day we can do a breaking change where the polyfill *requires* a global `DOMException` to exist, similar to [how we currently require a global `Promise` constructor](https://github.com/MattiasBuelens/web-streams-polyfill/blob/v3.2.0/README.md#compatibility). But that'd require Node 17 or higher, and it'll probably be a couple of years before we can safely drop support for Node < 17...

**Comment by jimmywarting** [comment]
it conditional depends on `worker_threads` (if it's a NodeJS env and the DOMException don't exist globally)
i always try to re-export the global if it exist so it should be quite browser friendly...

**Comment by MattiasBuelens** [comment]
As of Node 18 (specifically https://github.com/nodejs/node/commit/3f72c72bbb89154bc15fbcef7ccbe3cf0dd017ba), `AbortSignal.reason` defaults to an AbortError `DOMException`, so you can do this:
```javascript
const DOMException = AbortSignal.abort().reason.constructor;
```
This has the advantage that it doesn't use any Node-specific APIs (like `require`), and it works in modern browsers too (although you already have `globalThis.DOMException` there).

I could try to use that in this polyfill, so we'd have the "correct" `DOMException` in the latest version of Node *without* making a Node-specific polyfill. Perhaps you also want to use that in `node-domexception`? 🙂

**Comment by jimmywarting** [comment]
Tip https://github.com/jimmywarting/node-domexception

**Comment by MattiasBuelens** [comment]
Ah, never mind, Node 18 also ships with a global `DOMException` (https://github.com/nodejs/node/commit/e4b1fb5e6422c1ff151234bb9de792d45dd88d87), and that has landed *before* `AbortSignal.reason`.

It looks like `MessageChannel` is available as a global since Node 15. So I can already start using that (without depending on `worker_threads`), and wait until Node 14 goes EOL next year. 😛
