### ISSUE TITLE
Upgrading to Typescript 4.9 results in error TS2322 when using web-streams-polyfill

### ISSUE THREAD

**Issue by helenmg88** [MattiasBuelens/web-streams-polyfill#124]
Hello!! We have a type error when do this:
````
window.ReadableStream = ReadableStream;
````
Error:
```
Type 'typeof ReadableStream' is not assignable to type '{ new (underlyingSource: UnderlyingByteSource, strategy?: { highWaterMark?: number | undefined; } | undefined): ReadableStream<Uint8Array>; new <R = any>(underlyingSource: UnderlyingDefaultSource<...>, strategy?: QueuingStrategy<...> | undefined): ReadableStream<...>; new <R = any>(underlyingSource?: UnderlyingSourc...'.
  Types of parameters 'underlyingSource' and 'underlyingSource' are incompatible.
    Type 'UnderlyingSource<any> | undefined' is not assignable to type 'UnderlyingByteSource'.
      Type 'undefined' is not assignable to type 'UnderlyingByteSource'.
```
Do you plan to update the type? Thanks a lot!!

**Comment by MattiasBuelens** [comment]
I'm not sure if I can fix the polyfill types to be a perfect drop-in replacement for the TypeScript DOM types. Those types can also change with every TypeScript release, so it's tricky to keep up. 😕

If you can, I would actually recommend *not* overriding `window.ReadableStream`, and instead always importing from `web-streams-polyfill`:
```javascript
import { ReadableStream } from 'web-streams-polyfill';
const readable = new ReadableStream(/* ... */);
```

If you really *must* override it, then you could also use the `web-streams-polyfill/polyfill` variant and let it replace `window.ReadableStream` for you:
```javascript
import 'web-streams-polyfill/polyfill';
const readable = new ReadableStream(/* ... */);
```

**Comment by DhilipDKKumar** [comment]
Thanks for the response. I'm trying to import this polyfill for React-Native environment where the ReadableStream API is not implemented. So, I have no other option than to override the global declarations. The second option worked for me 🥳
