### ISSUE TITLE
welp, looking for that readableStream iterator polyfill

### ISSUE THREAD

**Issue by jimmywarting** [MattiasBuelens/web-streams-polyfill#128]
I remember somebody asking how to take a `ReadableStream` and turning it into a asyncIterator. 
I came with a suggestion and then you added some improvements to it. 

Don't remember where it was...
that person posted it somewhere in your repos i think...

**Comment by jimmywarting** [comment]
> I should really have put that in a Gist...

dito

Did you manage to find it again?

> nope, maybe i have to rewrite it. but i don't remember what your suggestions where to make it more spec compatible.

All i can say is that it started with `ReadableStream.prototype[Symbol.asyncIterator] ??=` 😅

Gona try searching my computer for it.

**Comment by jimmywarting** [comment]
found this in one readme file.
```js
import 'fast-readable-async-iterator'

// or

if (typeof ReadableStream !== 'undefined' && !ReadableStream.prototype[Symbol.asyncIterator]) {
  ReadableStream.prototype[Symbol.asyncIterator] = function () {
    const reader = this.getReader()
    let last = reader.read()
    return {
      next () {
        const temp = last
        last = reader.read()
        return temp
      },
      return () {
        return reader.releaseLock()
      },
      throw (err) {
        this.return()
        throw err
      },
      [Symbol.asyncIterator] () {
        return this
      }
    }
  }
}
```

And also this one:
```js
ReadableStream.prototype[Symbol.asyncIterator] ??= function () {
  const reader = this.getReader()
  return {
    next: _ => reader.read(),
    return: _ => { reader.releaseLock() },
    throw: err => {
      this.return()
      throw err
    },
    [Symbol.asyncIterator] () {
      return this
    }
  }
}
```

**Comment by MattiasBuelens** [comment]
Yeah, but those are still quite different from [the specced behavior](https://streams.spec.whatwg.org/#rs-asynciterator).

I would recommend something like this:
```js
ReadableStream.prototype.values ??= function({ preventCancel = false } = {}) {
    const reader = this.getReader();
    return {
        async next() {
            try {
                const result = await reader.read();
                if (result.done) {
                    reader.releaseLock();
                }
                return result;
            } catch (e) {
                reader.releaseLock();
                throw e;
            }
        },
        async return(value) {
            if (!preventCancel) {
                const cancelPromise = reader.cancel(value);
                reader.releaseLock();
                await cancelPromise;
            } else {
                reader.releaseLock();
            }
            return { done: true, value };
        },
        [Symbol.asyncIterator]() {
            return this;
        }
    };
};

ReadableStream.prototype[Symbol.asyncIterator] ??= ReadableStream.prototype.values;
```

**Comment by jimmywarting** [comment]
Thanks yet again for recreating the recommendations.

**Comment by jimmywarting** [comment]
You know... with this in place combined with a polyfill for `ReadableStream.from(iterable)` then this would make it a grate solution for converting your polyfilled `ReadableStream` instance into a native `ReadableStream` instance that could be transfered with `postMessage`.

```js
import { ReadableStream as Polyfill } from 'pkg'

var native = globalThis.ReadableStream.from(new Polyfill(...))
// and it would work the same the other way around
var polyfill = Polyfill.from(new globalThis.ReadableStream(...))
```

it would make the [web-streams-adapter](https://github.com/MattiasBuelens/web-streams-adapter) a bit obsolete.

kind of solves the conversion between node:streams to web streams as well when having a polyfill for `.from()` as well

**Comment by MattiasBuelens** [comment]
Yes, that was deliberate, see https://github.com/whatwg/streams/pull/1083#discussion_r598005739. 😁

I really need to find some time to work on `web-streams-polyfill` again and add `ReadableStream.from()`. Converting from a native `ReadableStream` or a Node.js `Readable` has always been painful with the polyfill (even when you use `web-streams-adapter`), and `from()` would help a lot.
