### ISSUE TITLE
Node version bump from 8 to 18 breaks Remix installation

### ISSUE THREAD

**Issue by Lms24** [MattiasBuelens/web-streams-polyfill#137]
Hi,

seems like [version 3.3.0 of `web-streams-polyfill`](https://github.com/MattiasBuelens/web-streams-polyfill/compare/v3.2.1...v3.3.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R32) bumps `engine` from Node 8 to Node 18 (https://github.com/MattiasBuelens/web-streams-polyfill/pull/130) which is higher than Remix' minimum Node version (Node 14). This in turn causes our (Sentry Javascript SDKs) integration tests to fail because Remix depends on `web-streams-polyfill`. 

![image](https://github.com/MattiasBuelens/web-streams-polyfill/assets/8420481/0a2402b5-e044-4b97-8fe2-e711652ed4ce)

IMHO a minimum node version bump should not be made in a minor release. We'll probably be able to work around this issue with overriding the dependency version but just wanted to let you know anyway! (I assume more remix users are going to run into this)

cheers!

**Comment by AbhiPrasad** [comment]
> Remove down-leveling for TypeScript 3.5 or lower

Removing down-leveling is also a breaking change for TS users. Some users are stuck on older TS versions because of transpilation incompatibilities (see https://github.com/getsentry/sentry-javascript/pull/2848 as an example we've run into). Is there appetite in making this a major version instead?

**Comment by MattiasBuelens** [comment]
Sorry about the inconvenience!

> IMHO a minimum node version bump should not be made in a minor release. We'll probably be able to work around this issue with overriding the dependency version but just wanted to let you know anyway! (I assume more remix users are going to run into this)

You're right about the `engines` bump, I shouldn't have done that. The polyfill should work fine when *installed* on Node 8, but *building* the polyfill requires a newer Node version (because of the build dependencies). I'll revert that.

> Removing down-leveling is also a breaking change for TS users. Some users are stuck on older TS versions because of transpilation incompatibilities (see [getsentry/sentry-javascript#2848](https://github.com/getsentry/sentry-javascript/pull/2848) as an example we've run into). Is there appetite in making this a major version instead?

Hmm, I didn't think users would still be using such old TypeScript versions... I'll see what I can do.

**Comment by feluna** [comment]
Could you release a quick fix version for this? Maybe with the latest commit of 3.2.0?  Some production systems are failing to build because of this.

**Comment by MattiasBuelens** [comment]
Version 3.3.1 is out. Can you check if that fixes it?

**Comment by feluna** [comment]
Yes, it works now. Thank you.

**Comment by MattiasBuelens** [comment]
Heads-up: I pushed a 3.3.2 release, since 3.3.1 was missing the `dist/types/polyfill.d.ts` file. 🤦‍♂️

**Comment by Lms24** [comment]
Thanks for the quick turnaround!
