### ISSUE TITLE
Upgrade to 4.0.0 from 3.3.3 causes type issues in node

### ISSUE THREAD

**Issue by bjornharrtell** [MattiasBuelens/web-streams-polyfill#145]
Runtime check x instanceof ReadableStream where x is an instance of ReadableStream in `web-streams-polyfill` was true in 3.3.3 but is false in 4.0.0.

**Comment by bjornharrtell** [comment]
I can get it to run under node by adding `import { ReadableStream } from 'web-streams-polyfill'` to the module doing the runtime check... but I'm thinking that is not good when the target for that module is (also) a browser.

**Comment by MattiasBuelens** [comment]
Could you provide a code example? I can't seem to reproduce:
```javascript
import 'web-streams-polyfill/polyfill';
import assert from 'node:assert';

const readable = new ReadableStream();
assert.ok(readable instanceof ReadableStream);
```
Please note that version 4.0 changed the default export to be the *ponyfill* variant. This means `import "web-streams-polyfill"` no longer modifies the global scope, instead you have to use `import "web-streams-polyfill/polyfill"`. [See the migration guide.](https://github.com/MattiasBuelens/web-streams-polyfill/blob/v4.0.0/MIGRATING.md)

**Comment by bjornharrtell** [comment]
Thanks and sorry for the noise! I should have studied the release nodes and migration guide better, no issue after doing it right.
