### ISSUE TITLE
Queue size performance issue

### ISSUE THREAD

**Issue by matthiasbayer** [MattiasBuelens/web-streams-polyfill#15]
Hi,

thanks for maintaining this repo, great work!  

Are you aware of the performance issues mentioned here:
* Chromium Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=681493
* Explaination: https://groups.google.com/forum/#!msg/v8-users/Hj78A4yhQS4/edz6-NsyCAAJ
* Issue on sd-streams repo: https://github.com/stardazed/sd-streams/issues/1

I created a CodePen using the code from the bug report:
* Native: https://codepen.io/anon/pen/gEpXXb
![image](https://user-images.githubusercontent.com/1780547/54442056-3a1c7a00-473e-11e9-9961-f2e69f5b0c7b.png)

* Polyfill: https://codepen.io/anon/pen/EMEoaa
![image](https://user-images.githubusercontent.com/1780547/54442084-47396900-473e-11e9-96e1-be2a58504bca.png)

I'd like to use this polyfill in production, but the performance drop, even if unlikely to happen, is a very bad experience for the user. 

Do you think it's possible to include a fix (e.g. something like https://github.com/stardazed/sd-streams/commit/1128f0d49e6bfaab23de703dee2f84b03ff3039b) into this repository? Or is this not possible because it would be non-standard?

Looking forward to hear you opinion on this.

**Comment by MattiasBuelens** [comment]
Ouch, that's quite the performance hit. Thanks for reporting!

I'll look into doing something similar to `sd-streams` for this polyfill. I'm okay with diverting from the reference implementation, as long as we keep passing all web platform tests. 🙂
