### ISSUE TITLE
Can't load the plugin with typescript 3.2.2

### ISSUE THREAD

**Issue by azakaryan** [MattiasBuelens/web-streams-polyfill#39]
When I try to load the plugin into angular7 project I get an Error
`ERROR in node_modules/web-streams-polyfill/dist/types/polyfill.d.ts(1,21): error TS2727: Cannot find lib definition for 'es2018.asynciterable'. Did you mean 'esnext.asynciterable'?`

I did some investigations and it seems the cause is typescript version I have. 3.2.2

NOTE it works as expected with typescript version 3.5.3 that I have in angular 8 app

I can't upgrade typescript version since it's required by angular 7. The only way to make your polyfill to work is to upgrade to angular 8.

It seems that in typescript 3.2  `asynciterable` is under esnext.asynciterable instead of es2018.asynciterable. 

Please advise. Thank you in advanced.

**Comment by MattiasBuelens** [comment]
Indeed, TypeScript 3.2 was released before async iterables were added to the JavaScript standard, so they were still in `esnext.asynciterable`.

Interestingly, TypeScript 3.5 has both `es2018.asynciterable` and `esnext.asynciterable` [for backwards compatibility](https://github.com/microsoft/TypeScript/pull/26220/files#r254474573). So I can make the polyfill use the old name and support both old and new TypeScript versions.

I'll look into it. Thanks for reporting! 🙂

**Comment by azakaryan** [comment]
@MattiasBuelens when do you think it will be released ?

**Comment by MattiasBuelens** [comment]
I was considering if I wanted to put anything else in this release. But I can always make another release later. 😄 

Released as [v2.0.6](https://github.com/MattiasBuelens/web-streams-polyfill/releases/tag/v2.0.6).

**Comment by azakaryan** [comment]
Thank you very much :)
