### ISSUE TITLE
close missing?

### ISSUE THREAD

**Issue by jimmywarting** [MattiasBuelens/web-streams-polyfill#43]
tried to use `new WritableStream().close()` but that failed with the polyfill

https://streams.spec.whatwg.org/#ws-close

---

Realize i tried it in canary and didn't notice any error.
chrome stable don't have it yet.

**Comment by MattiasBuelens** [comment]
The polyfill is currently aligned with [spec version `ae5e0cb`](https://streams.spec.whatwg.org/commit-snapshots/ae5e0cb41e9f72cdd97f3a6d47bc674c1f4049d1/) from August 2019. I guess it's time for an update. 😃
