### ISSUE TITLE
breaking change around abortsignal?

### ISSUE THREAD

**Issue by jimmywarting** [MattiasBuelens/web-streams-polyfill#56]
When I changed from v2.1.0 to v2.1.1 then a promise would never reject as it should have done.

```js
const abortController = new AbortController()
abortController.abort()
const promise = readable.pipeTo(writable, { signal: abortController.signal })
await promise.catch(console.log)
```

The result was that it just hangs and waits.
(aborting something synchronously is abnormal since this is just a mocha test)
I tried creating a minimal reproducible code but was unable to just do it with just purely WritableStream + ReadableStream
I'm extending/waiting/writing stuff

**Comment by MattiasBuelens** [comment]
Huh? That's odd. There shouldn't be any behavioral changes [between v2.1.0 and v2.1.1](https://github.com/MattiasBuelens/web-streams-polyfill/compare/v2.1.0...v2.1.1), I merely tweaked the types a bit... 😕 

Are you running this inside Node? What `AbortController` polyfill are you using? Could you perhaps make a repository with a complete reproduction case?

This works fine for me (although I'm using Jasmine instead of Mocha):
```javascript
const { ReadableStream, WritableStream } = require('web-streams-polyfill');
const { AbortController } = require('abortcontroller-polyfill/dist/abortcontroller');

describe('ReadableStream', () => {
  it('issue #56', async () => {
    const readable = new ReadableStream({});
    const writable = new WritableStream({});
    const abortController = new AbortController();
    abortController.abort();
    const promise = readable.pipeTo(writable, { signal: abortController.signal });
    await promise.catch(console.log);
  });
});
```

**Comment by MattiasBuelens** [comment]
> I tried creating a minimal reproducible code but was unable to just do it with just purely WritableStream + ReadableStream
> I'm extending/waiting/writing stuff

Oh woops, I missed that. Okay, ignore my example code then. 😅

If you find some way to reproduce it, let me know. 🙂

**Comment by jimmywarting** [comment]
> If you find some way to reproduce it, let me know. 🙂

tried like 1 hour debugging and commenting out some of my code yesterday.
I'm using it in firefox/safari and i'm using the native AbortSignal
the polyfill isn't loaded in chrome since it use native instead.
will try later to reproduce again. must be some race condition or something 

(even ended up writing the same code you did)
