### ISSUE TITLE
signal with pre aborted 

### ISSUE THREAD

**Issue by jimmywarting** [MattiasBuelens/web-streams-polyfill#75]
In one of my test, this hangs indefinitely when using a abort signal that have already been canceled togheter with polyfill (this don't happen when using natives)

```js
  const abortController = new AbortController()
  const signal = abortController.signal
  abortController.abort()
  const promise = rs.pipeTo(ws, { signal })
  err = await promise.catch(e=>e)
  // never gets here
```

version using 3.0.3 (edit: and 3.0.1 apparently)

**Comment by MattiasBuelens** [comment]
I can't seem to reproduce this. 😕 

I tried adding your code as a unit test [here](https://github.com/MattiasBuelens/web-streams-polyfill/blob/v3.0.3/test/unit/readable-stream/regression.spec.js), and I see `err` is set to a `DOMException` as expected. There's even [a WPT test for this case](https://github.com/web-platform-tests/wpt/blob/0895a4d4a2681c4d892bfeb90cc8188db75cbce0/streams/piping/abort.any.js#L36-L54), and the polyfill passes it without a problem.

* Could you link to a repository with a reproduction case?
* What environment are you using? A browser (if so: which, and what version)? Or Node (if so: what version)?

**Comment by jimmywarting** [comment]
Found out what the problem was... i did use two different versions of the ponyfill 
Somehow everything worked out just fine, everything was interchangeable between different versions, it could be pipe/read/written to different versions. It could basically do everything. Everything except the signal

Here is a reproducible test case

```js
import('https://cdn.jsdelivr.net/npm/web-streams-polyfill@3.0.0/dist/ponyfill.es2018.mjs').then(async vers300 => {
  const vers301 = await import('https://cdn.jsdelivr.net/npm/web-streams-polyfill@3.0.1/dist/ponyfill.es2018.mjs')
 
  const rs = new vers300.ReadableStream()
  const ws = new vers301.WritableStream()
  const abortController = new AbortController()
  abortController.abort()
  rs.pipeTo(ws, { signal: abortController.signal })
})
```
...And a [fiddle](https://jimmywarting.github.io/native-file-system-adapter/example/test.html)

Here are all the test i run: https://jimmywarting.github.io/native-file-system-adapter/example/test.html

**Comment by jimmywarting** [comment]
Really looking forward to #20 being resolved

**Comment by MattiasBuelens** [comment]
Aaaah, I see. The classes from two different versions are *seemingly* compatible: all public properties and public methods are the same, and even the internal property names like `_readableStreamController` are unchanged. Except for one small but crucial difference: the private symbols such as `[[PullSteps]]` and `[[ErrorSteps]]`.

Thus, when version 3.0.0's `ReadableStreamPipeTo()` wants to abort a `WritableStream` from version 3.0.1, it eventually tries to call `stream._writableStreamController[ErrorSteps]()` [in WritableStreamFinishErroring](https://github.com/MattiasBuelens/web-streams-polyfill/blob/v3.0.1/src/lib/writable-stream.ts#L411). It will look up the `ErrorSteps` symbol from version 3.0.0, but that won't exist on the `WritableStream` create with version 3.0.1. So this function unexpectedly errors, and the pipe promise never resolves.

I suppose I could improve `IsReadableStream` to check that `stream._readableStreamController` is an instance of *our own* `ReadableStreamDefaultController` or `ReadableByteStreamController`, and similarly for `IsWritableStream` and our own `WritableStreamDefaultController`. 🤔

> Really looking forward to #20 being resolved so i can use that instead.
> (just patching the missing pieces)

I know, I know. 😛

**Comment by jimmywarting** [comment]
That was mostly Greek to me. but Sound like you know got it figured out 👍
