### ISSUE TITLE
Issue with dynamic import

### ISSUE THREAD

**Issue by fryck** [MattiasBuelens/web-streams-polyfill#94]
Hello,

I use native-file-system-adapter which have a dependency to `web-streams-polyfill` this library try to dynamically import `web-streams-polyfill` when I try to build my app (webpack5 / typescript 4.4) I have this error:

```
external "https://cdn.jsdelivr.net/npm/web-streams-polyfill@3/dist/ponyfill.es2018.mjs"
The target environment doesn't support dynamic import() syntax so it's not possible to use external type 'module' within a script
```

Could you help me ? thanks !

**Comment by MattiasBuelens** [comment]
`native-file-system-adapter` appears to target `esnext` with `esnext` module support ([source](https://github.com/jimmywarting/native-file-system-adapter/blob/2b3f98102d930a9af629ddbd58bbe3e1fe5f80fe/tsconfig.json#L4-L5)), so it only supports modern browsers. However, it sounds like you've configured your webpack app to target older browsers that *do not* support dynamic `import()`s.

Either way, there are no dynamic `import()`s inside the polyfill itself, so this is not a problem with the polyfill. I suggest you continue this discussion in jimmywarting/native-file-system-adapter#20.

**Comment by fryck** [comment]
Thanks for your reply, I've tried to build my app with `target: 'esnext'` and `module: 'esnext'` but I got the same error.

**Comment by jimmywarting** [comment]
fyi native-file-system-adapter no longer use async import
